### ISSUE TITLE
template.yml does not work with localstack.

### ISSUE THREAD

**Issue by tom-huguenard** [aws-samples/aws-plaid-demo-app#192]
Can you please have a look into this? With a localstack Pro licence, I am able to run samlocal.py (provided by localstack) to run the sam deploy command to create all services locally. It fails though. I have modified it to try to get it to work, but I am not sure how to proceed.

I would appreciate any help you might offer.

**Comment by jplock** [comment]
I’ve never tested this with local stack and not familiar enough with what may or may not be supported. Is there a specific resource or error message you are receiving that indicates an issue?

**Comment by tom-huguenard** [comment]
Thank you for your assistance. I am pretty sure you will tell me it is a localstack issue if I provide an error message. And direct me to have them take a whack at at. So, never mind. Let's just close the issue and move on with our lives.
