### ISSUE TITLE
Creating new account doesn't work out of the box

### ISSUE THREAD

**Issue by carlos-alzate** [aws-samples/aws-plaid-demo-app#38]
Trying to create a new account leads to the following error in the console:

[ERROR] 58:36.432 AuthError - 
            Error: Amplify has not been configured correctly. 
            The configuration object is missing required auth properties.
            This error is typically caused by one of the following scenarios:

            1. Did you run `amplify push` after adding auth via `amplify add auth`?
                See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information

            2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.

I haven't been able to add the `auth` feature either on the Amplify CLI or console.

**Comment by jplock** [comment]
Please try again with the last code commit from today.  There seemed to be an issue with one of the nested Amplify dependencies that was causing that error.

**Comment by carlos-alzate** [comment]
Great, it works now! Thanks!
