### ISSUE TITLE
Frontend url not displaying the app

### ISSUE THREAD

**Issue by JohnRuffin** [aws-samples/aws-plaid-demo-app#68]
Greetings, I followed the directions to build and deploy the demo app. No errors in CloudFormation logs. I can see the frontend url in the console output, CloudFormation output, and in the Amplify Domain management tab. When clicking the frontend url link, I get: 

```
Welcome
Your app will appear here once you complete your first deployment.
Deployment didn't work? Here are some options:

Check out [our docs](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html)
Click the Feedback button in the bottom-left corner of the service page
Quick tips:

Have you checked your build settings? The baseDirectory parameter in the artifacts step of your YAML file should match your build output directory
Building your app should produce an index.html file. Try building your app locally and check a file with that name exists in the artifacts base directory. 
```

Did I miss a step in the documentation here?

**Comment by jplock** [comment]
Can you try going into Amplify and ensure it’s built the application at least once?

**Comment by JohnRuffin** [comment]
Thank you @jplock! I manually triggered the build in the Amplify console and noticed my GitHub MFA was hosing up the build connectivity. I gave Amplify permission to the single GitHub app in the repo and the Amplify build succeeded - app loading now!!!!

**Comment by JohnRuffin** [comment]
So, I got past the Amplify to GitHub connectivity hiccup. Also, there is a new Time-based One Time Password screen that should be documented. I'll issue a PR for that. But past the TOTP, I'm getting an error in  handleGetToken().  Please see screenshot.

![Screen Shot 2023-04-22 at 5 09 13 AM](https://user-images.githubusercontent.com/209990/233778239-6b066c80-51e7-4c07-8f75-69c9230b6b78.png)

**Comment by jplock** [comment]
Can you see if there are errors in the CloudWatch Logs for the Lambda function?
